### ISSUE TITLE
Transcode text content-types to/from utf8

### ISSUE THREAD

**Issue by Kehrlann** [projectriff/streaming-http-adapter#13]
- The streaming HTTP adapter should decode the payload of the incoming request based on the charset declared in the `content-type`, and re-encode it in utf-8 before making the gRPC call.
- It should assume the functions return utf-8-encoded payloads for text-based protocols.
- It should encode the output of the functions to match one the "Accept-charset" headers from the HTTP request.

This issue follows discussions in https://github.com/projectriff/node-function-invoker/issues/109

**Comment by ericbottard** [comment]
I'm not yet convinced this is a good idea, in particular if there are characters that can't be encoded in utf-8 (are there any apart from \u0000?).

In any case, I whole heartly disagree with 
> It should assume the functions return utf-8-encoded payloads for text-based protocols.

for both understandings of "assume":
- if nothing is specified, nothing should be assumed apart from what is in the spec for a *particular* textual format (for example, is the "default" for text/xml the same as application/json?)
- more importantly, the proxy should be ready to accept anything.

**Comment by Kehrlann** [comment]
Ok I won't go on implementing anything just yet ; I understood from the mentioned issue that there was consensus on doing this transcoding in the adapter 😅

I believe all Unicode code points are covered by utf-8 (https://stackoverflow.com/questions/5924105/how-many-characters-can-be-mapped-with-unicode). I don't think \u0000 is a special case ; all ASCII characters map directly to utf-8, and the null byte is just an ascii character ... ?

_Re: outbound transcoding_
Ah great point, I think I mixed a things a little bit. Here's a more detailed spec: 
1. If the HTTP call has a "Accept-charset" header set to latin1, and the invoker/function returns a payload with a "Content-Type" of say, utf-8, then the adapter should transcode utf-8 to latin1.
2. If "Accept-charset" and "content-type" are the same, the adapter just forwards the raw payload.
3. If there are multiple charsets defined in the "Accept-charset" header, and the invoker/function specifies "Content-type" header, then the adapter will try to transcode from Content-Type to the appropriate charsets, taking "Quality" values into account (see RFC 7231 https://tools.ietf.org/html/rfc7231#section-5.3.3)
4. If there is no "Accept-charset" defined, the adapter will forward the raw payload.
5. Finally, if  there is an "accept-charset" defined, but the invoker/function does not return a Content-Type header ... Then what should the adapter do ? Forward the raw payload, assume the response was utf-8 and transcode from that, return a "406 Not Acceptable" ?
